const http = require('http');

class DSLRBoothAPI {
    /**
     * @param {string} host  - DSLRBooth machine IP/hostname
     * @param {number} port  - API port (default 8080)
     * @param {string} password - API password generated by DSLRBooth
     */
    constructor(host = '127.0.0.1', port = 8080, password = '') {
        this.host = host;
        this.port = port;
        this.password = password;
    }

    /**
     * Build the base URL for API calls
     */
    _baseUrl(endpoint) {
        const pw = this.password ? `?password=${encodeURIComponent(this.password)}` : '';
        return `http://${this.host}:${this.port}${endpoint}${pw}`;
    }

    /**
     * Send an HTTP GET request to DSLRBooth
     */
    sendCommand(endpoint) {
        return new Promise((resolve, reject) => {
            const url = this._baseUrl(endpoint);
            http
                .get(url, (res) => {
                    let data = '';
                    res.on('data', (chunk) => (data += chunk));
                    res.on('end', () => {
                        try {
                            resolve(JSON.parse(data));
                        } catch {
                            resolve(data);
                        }
                    });
                })
                .on('error', (err) => reject(err));
        });
    }

    /** Get DSLRBooth status */
    getStatus() {
        return this.sendCommand('/api/status');
    }

    /** Start a Print session */
    startPrint() {
        return this.sendCommand('/api/start/print');
    }

    /** Start a GIF session */
    startGIF() {
        return this.sendCommand('/api/start/gif');
    }

    /** Start a Boomerang session */
    startBoomerang() {
        return this.sendCommand('/api/start/boomerang');
    }

    /** Start a Video session */
    startVideo() {
        return this.sendCommand('/api/start/video');
    }

    /** Lock the screen */
    lock() {
        return this.sendCommand('/api/lock');
    }

    /** Unlock the screen */
    unlock() {
        return this.sendCommand('/api/unlock');
    }

    /** Stop current session */
    stop() {
        return this.sendCommand('/api/stop');
    }
}

module.exports = DSLRBoothAPI;
